name: poison
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0  # Explicitly keep numpy at version 1.x
  - scipy=1.10.0
  - scikit-learn  # Added missing sklearn package
  - pip:
    - torch==1.11
    - transformers==4.20.1
    - tokenizers==0.12.1
    - spacy
    - tqdm
    - wandb
    - datasets