name: poison
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Using 3.8 which has better compatibility with most packages
  - numpy=1.21.6
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pytorch=1.11.0
  - cpuonly
  - pip
  - pip:
    - transformers==4.20.1
    - tokenizers==0.12.1
    - spacy==3.2.0  # Adding specific spacy version
    - tqdm
    - wandb
    - datasets